// SND's embedded icon fonts. Material Icons (Apache-2.0) is merged into the
// default text font so ICON_MD_* works inline; Lucide (ISC) is a second font
// (its Private-Use codepoints overlap Material's, so it can't merge into the
// same font). The big compressed TTF arrays live in their own translation unit
// so they don't slow the rest of ui.cpp's compile. Loaded per ImGui context
// (SND makes one context per window) from Window::create.
#include "snd/icons.h" // ICON_MIN_MD / ICON_MAX_16_MD / ICON_MIN_LC / ICON_MAX_LC
#include "snd/ui.h"

#include "imgui.h"

// generated by ImGui's binary_to_compressed_c -base85 (see third_party/fonts)
#include "fonts/material.inc" // MaterialIcons_compressed_data_base85
#include "fonts/lucide.inc"   // Lucide_compressed_data_base85

namespace snd::ui {

void loadFonts()
{
    ImGuiIO& io = ImGui::GetIO();

    // Explicit reference sizes throughout: ImGui 1.92 forbids merging a
    // fixed-size font into an implicit-size one, and needs a >0 size to bake a
    // glyph. Per-draw sizing still works -- the icon button draws at an
    // explicit pixel size regardless of this reference.
    ImFontConfig def;
    def.SizePixels = 13.0f;         // ProggyClean's native size
    io.Fonts->AddFontDefault(&def); // font 0: text

    // merge Material into the default font -> ICON_MD_* usable inline with text
    ImFontConfig merge;
    merge.MergeMode = true;
    merge.PixelSnapH = true;
    static const ImWchar mdRange[] = { ICON_MIN_MD, (ImWchar) ICON_MAX_16_MD, 0 };
    io.Fonts->AddFontFromMemoryCompressedBase85TTF(MaterialIcons_compressed_data_base85,
                                                   13.0f, &merge, mdRange);

    // Lucide as its own font (font 1)
    static const ImWchar lcRange[] = { ICON_MIN_LC, (ImWchar) ICON_MAX_LC, 0 };
    io.Fonts->AddFontFromMemoryCompressedBase85TTF(Lucide_compressed_data_base85, 16.0f,
                                                   nullptr, lcRange);
}

ImFont* iconFontMaterial()
{
    ImFontAtlas* a = ImGui::GetIO().Fonts;
    return a->Fonts.empty() ? nullptr : a->Fonts[0]; // default (Material merged in)
}

ImFont* iconFontLucide()
{
    ImFontAtlas* a = ImGui::GetIO().Fonts;
    return a->Fonts.Size > 1 ? a->Fonts[1] : iconFontMaterial();
}

} // namespace snd::ui
